-- vim.g.copilot_no_tab_map = true -- Disable default <Tab> mapping
--
-- -- Use <C-l> to accept the suggestion
-- vim.keymap.set("i", "<C-l>", 'copilot#Accept("<CR>")', {
--   expr = true,
--   replace_keycodes = false,
-- })
